apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-java-maven
  labels:
    app: azdevops-agent-ubuntu-java-maven
spec:
  replicas: 1 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent-ubuntu-java-maven
  template:
    metadata:
      labels:
        app: azdevops-agent-ubuntu-java-maven
    spec:
      containers:
      - name: devops-agent-ubuntu-java-maven
        image: mwitacrkoreacentral.azurecr.io/devops-agent-ubuntu-java-maven:16.04
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock